### ISSUE TITLE
Posible valor NULL en rm_layers en función find_best_model.R

### ISSUE THREAD

**Issue by palmoreck** [luismurao/hsi#1]
Hola Luis,

Le estoy ayudando a Mariana de CONABIO del grupo de Michael Schmidt a correr un script que utiliza tu función referida en el título de este issue `find_best_model.R` Me pasó sus datos y empecé a correr en una máquina su código hasta la línea que manda a llamar la función pero obtiene este error:

```
Error in -rm_layers: invalid argument to unary operator
Traceback:

1. find_best_model(this_species = e_test, cor_threshold = 0.8, ellipsoid_level = 0.975, 
 .     nvars_to_fit = 3, E = 0.05, RandomPercent = 70, NoOfIteration = 1000, 
 .     parallel = TRUE, n_cores = 2, plot3d = FALSE)
2. stats::na.omit(env_train[, -rm_layers])
3. env_train[, -rm_layers]
4. `[.data.frame`(env_train, , -rm_layers)
```

Después de ejecutar las líneas iniciales de la función observé que en la línea [find_best_model.R#L26](https://github.com/luismurao/hsi/blob/master/R/find_best_model.R#L26) se tiene NULL

```
rm_layers <- unlist(sapply( 1:dim(env_train)[2], function(x){
  if(length(which(is.na(env_train[,x]))) > n_nas) return(x)
} ))
rm_layers
NULL
```

Por lo que la siguiente línea falla:

```
env_train <- stats::na.omit(env_train[,-rm_layers])

Error in -rm_layers: invalid argument to unary operator
Traceback:

1. stats::na.omit(env_train[, -rm_layers])
2. env_train[, -rm_layers]
3. `[.data.frame`(env_train, , -rm_layers)
```

Si `rm_layers` no fuera `NULL` por ejemplo:

```
env_train <- stats::na.omit(env_train[,-1])
```

entonces no hay fallo. 

¿Podrías corroborar si debería ser diferente de `NULL` la línea del código?

Muchas gracias por tu desarrollo de `hsi` :)

Saludos

**Comment by luismurao** [comment]
Estimado @palmoreck,
Primero que nada, gracias por reportar este issue. Tienes razón, el problema tiene que ver con ese argumento NULL de [find_best_model.R#L26](https://github.com/luismurao/hsi/blob/4039734436396e48a10721d1c7fde988f38dbf34/R/find_best_model.R#L26). Habrá que ver si el número de NAs de cada variable ambiental en los datos de entrenamiento es mayor al 10% de los mismos ([ver aqui](https://github.com/luismurao/hsi/blob/4039734436396e48a10721d1c7fde988f38dbf34/R/find_best_model.R#L23)) . Puedes ver en tu ejemplo si es este el caso?
Saludos al equipo!

**Comment by palmoreck** [comment]
Muy bien @luismurao 

Voy a revisar el número de NAs con mi equipo y te informamos lo antes posible.

Muchas gracias por tu respuesta.

Saludos!
